ClassManager/ClassManager/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

curso/urls.py
from django.urls import path
from . import views

app_name = 'curso'

urlpatterns = [
    path('', views.curso, name='curso'),
    path('verCurso/<id_curso>', views.verCurso, name='ver_curso'),
    path('editarCurso/<id_curso>/', views.editarCurso, name='editar_curso'),
    path('eliminarCurso/<id_curso>/', views.eliminarCurso, name='eliminar_curso'),
]

gestion_alumnos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('', include('index.urls')),
    path('alumnos/', include('alumnado.urls')),
    path('asistencia/', include('asistencia.urls')),
    path('curso/', include('curso.urls')),
    path('notas/', include('notas.urls')),
    path('especialidad/', include('especialidad.urls')),
    path('materias/', include('materia.urls')),
    path('personal/', include('personal.urls')),
    path('agenda/', include('agenda.urls'))
]

personal/urls.py
from django.urls import path
from . import views

app_name = 'personal'

urlpatterns = [
    path('', views.personal, name='personal'),
    path('verPersonal/<id_personal>', views.verPersonal, name='ver_personal'),
    path('editarPersonal/<id_personal>/', views.editarPersonal, name='editar_personal'),
    path('eliminarPersonal/<id_personal>/', views.eliminarPersonal, name='eliminar_personal'),
]

personal/models.py
from django.db import models
from materia import models as materia_models

# Create your models here.

class Personal(models.Model):
    id_personal = models.AutoField(primary_key=True)
    dni_p = models.CharField(max_length=9)
    cuil_p = models.CharField(max_length=15)
    apellido_p = models.CharField(max_length=50)
    nombre_p = models.CharField(max_length=50)
    legajo_p = models.CharField(max_length=10)
    telefono_p = models.CharField(max_length=20, blank=True)
    direccion_p = models.CharField(max_length=50, blank=True)
    fecha_nac_p = models.DateField()
    copiaDNI_p = models.ImageField(upload_to='personal/images/', blank=True)
    rol_p = models.CharField(max_length=50, blank=True)
    id_materia = models.ForeignKey(materia_models.Materia, on_delete=models.CASCADE, default=0)

    def __str__(self):
        texto = "{0}, {1} ({2})"
        return texto.format(self.apellido_p, self.nombre_p, self.id_personal)

personal/forms.py
from django import forms
from .models import Personal


class PersonalForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['fecha_nac_p'].widget = forms.widgets.DateInput(
            attrs={
                'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)',
                'class': 'form-control'
            }
        )

    class Meta:
        model = Personal
        fields = ['id_personal', 'dni_p', 'cuil_p', 'apellido_p', 'nombre_p',
                  'legajo_p', 'telefono_p', 'direccion_p', 'fecha_nac_p', 'copiaDNI_p', 'rol_p', 'id_materia']


class PersonalFormUpdate(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['fecha_nac_p'].widget = forms.widgets.DateInput(
            attrs={
                'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)',
                'class': 'form-control'
            }
        )

    class Meta:
        model = Personal
        fields = ['id_personal', 'dni_p', 'cuil_p', 'apellido_p', 'nombre_p',
                  'legajo_p', 'telefono_p', 'direccion_p', 'fecha_nac_p', 'copiaDNI_p', 'rol_p', 'id_materia']

personal/views.py
from django.shortcuts import render, redirect
from .models import Personal
from .forms import PersonalForm, PersonalFormUpdate

# Create your views here.
def personal(request):
    personal_form = PersonalForm()
    personal = Personal.objects.all()


    if request.method == 'POST':
        personal_form = PersonalForm(data=request.POST)

        if personal_form.is_valid():
            personal_form.save()
            return redirect('/personal')
    context = {
        'personal_form' :personal_form,
        'personal': personal
    }
    
    return render(request, 'gestion_personal.html', context)

def verPersonal(request, id_personal):
    personal = Personal.objects.get(id_personal=id_personal)
    return render(request, "verPersonal.html", {"personal": personal})  

def editarPersonal(request, id_personal):
    queryset = Personal.objects.get(id_personal=id_personal)
    personal_form_update = PersonalFormUpdate(instance=queryset)
    if request.method == 'POST':
        personal_form_update = PersonalFormUpdate(request.POST, instance=queryset)
        if personal_form_update.is_valid():
            personal_form_update.save()
            return redirect('/personal')
    
    context = {
		'personal_form_update':personal_form_update,
	}
    return render(request, 'edicionPersonal.html', context)

def eliminarPersonal(request, id_personal):
    personal = Personal.objects.get(id_personal=id_personal)
    personal.delete()

    return redirect('/personal')

personal/templates/edicionPersonal.html
{% extends "./base.html" %} 
{% block title %}Edicion PERSONAL {%endblock%} 
{% block body %}
{% load crispy_forms_tags %}
<h2>EDICION DE PERSONAL</h2>

<form action="" method="POST">
{% csrf_token %} 
{{ personal_form_update|crispy}}
<button type="submit" class="btn btn-success btn-block text-white">
  Guardar
</button>
</form>

{% endblock %}

personal/templates/gestion_personal.html
{% extends "./base.html" %} {% block title %}GESTION DE PERSONAL{%endblock%} 
{% block body %} {% load crispy_forms_tags %}
<div class="row">
  <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4 bg-info">
    <h2>GESTION DE PERSONAL</h2>
    <div class="card bg-info">
      <div class="card-body bg-info">
        <form action="" method="POST">
          {% csrf_token %} {{ personal_form|crispy}}

          <button type="submit" class="btn btn-success btn-block text-white">
            Guardar
          </button>
      </div>
    </div>
  </div>
  <div class="col-sm-12 col-md-6 col-lg-8 col-xl-8 bg-info">
    <h1>INFORMACION DE PERSONAL</h1>
    <div class="table-responsive py-2">
      <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>Legajo</th>
            <th>Apellido</th>
            <th>Nombre</th>
            <th>DNI</th>
            <th colspan="3">
              <center>MENU</center>
            </th>
          </tr>
        </thead>
        <tbody>
          {% for perso in personal%}
          <tr>
            <td>{{perso.legajo_p}}</td>
            <td>{{perso.apellido_p}}</td>
            <td>{{perso.nombre_p}}</td>
            <td>{{perso.dni_p}}</td>
            <td>
              <a
                href="{% url 'personal:ver_personal' perso.id_personal%}"
                class="btn btn-success"
                >Ver</a
              >
            </td>
            <td>
              <a
                href="{% url 'personal:editar_personal' perso.id_personal%}"
                class="btn btn-info"
                >Editar</a
              >
            </td>
            <td>              
              <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                Eliminar
              </button>
              <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Confirmar Eliminación</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      ¿Desea eliminar este Personal?
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <a href="{% url 'personal:eliminar_personal' perso.id_personal%}" class="btn btn-danger">Eliminar</a>
                    </div>
                  </div>
                </div>
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}

personal/templates/verPersonal.html
{% extends "./base.html" %} {% block title %}Edicion Alumno {%endblock%} 
{% block body %}

<div class="col-sm-12 col-md-6 col-lg-8 col-xl-8" bg-color="#80000">
  <h2>
    INFORMACION DE PERSONAL {{personal.apellido_p}}, {{personal.nombre_p}}
  </h2>
  <table class="table table-info">
    <thead>
      <th>Tipo</th>
      <th>Dato</th>
    </thead>
    <tbody>
      <tr>
        <td>ID</td>
        <td>{{personal.id_personal}}</td>
      </tr>
      <tr>
        <td>DNI</td>
        <td>{{personal.dni_p}}</td>
      </tr>
      <tr>
        <td>CUIL</td>
        <td>{{personal.cuil_p}}</td>
      </tr>
      <tr>
        <td>APELLIDO</td>
        <td>{{personal.apellido_p}}</td>
      </tr>
      <tr>
        <td>NOMBRE</td>
        <td>{{personal.nombre_p}}</td>
      </tr>
      <tr>
        <td>LEGAJO</td>
        <td>{{personal.legajo_p}}</td>
      </tr>
      <tr>
        <td>TELEFONO</td>
        <td>{{personal.telefono_p}}</td>
      </tr>
      <tr>
        <td>DIRECCION</td>
        <td>{{personal.direccion_p}}</td>
      </tr>
      <tr>
        <td>FECHA DE NACIMIENTO</td>
        <td>{{personal.fecha_nac_p}}</td>
      </tr>
      <tr>
        <td>COPIA DE DNI</td>
        <td>{{personal.copiaDNI_p}}</td>
      </tr>
      <tr>
        <td>ROL</td>
        <td>{{personal.rol_p}}</td>
      </tr>
      <tr>
        <td>ID DE MATERIA</td>
        <td>{{personal.id_materia}}</td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}