ClassManager/ClassManager/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

agenda/urls.py
from django.urls import path
from . import views

app_name = 'agenda'

urlpatterns = [
    path('', views.agenda, name='agenda'),
    path('verAgenda/<id_agenda>', views.verAgenda, name='ver_agenda'),
    path('editarAgenda/<id_agenda>/', views.editarAgenda, name='editar_agenda'),
    path('eliminarAgenda/<id_agenda>/', views.eliminarAgenda, name='eliminar_agenda'),
]

curso/urls.py
from django.urls import path
from . import views

app_name = 'curso'

urlpatterns = [
    path('', views.curso, name='curso'),
    path('verCurso/<id_curso>', views.verCurso, name='ver_curso'),
    path('editarCurso/<id_curso>/', views.editarCurso, name='editar_curso'),
    path('eliminarCurso/<id_curso>/', views.eliminarCurso, name='eliminar_curso'),
]

gestion_alumnos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('', include('index.urls')),
    path('alumnos/', include('alumnado.urls')),
    path('asistencia/', include('asistencia.urls')),
    path('curso/', include('curso.urls')),
    path('notas/', include('notas.urls')),
    path('especialidad/', include('especialidad.urls')),
    path('materias/', include('materia.urls')),
    path('personal/', include('personal.urls')),
    path('agenda/', include('agenda.urls'))
]

agenda/models.py
from django.db import models
from personal import models as personal_models

# Create your models here.

class Agenda(models.Model):
    id_agenda = models.AutoField(primary_key=True)
    fecha_hora = models.DateTimeField(auto_now_add=True,verbose_name='Hora')
    descripcion = models.TextField()
    id_personal = models.ForeignKey(personal_models.Personal, on_delete=models.CASCADE, default=0)

    def __str__(self):
        texto = "{0}"
        return texto.format(self.id_personal)

agenda/forms.py
from django import forms
from .models import Agenda


class AgendaForm(forms.ModelForm):

    class Meta:
        model = Agenda
        fields = ['id_agenda', 'descripcion', 'id_personal']


class AgendaFormUpdate(forms.ModelForm):

    class Meta:
        model = Agenda
        fields = ['id_agenda', 'descripcion', 'id_personal']

agenda/views.py
from django.shortcuts import render, redirect
from .models import Agenda
from .forms import AgendaForm, AgendaFormUpdate

# Create your views here.
def agenda(request):
    agenda_form = AgendaForm()
    agenda = Agenda.objects.all()


    if request.method == 'POST':
        agenda_form = AgendaForm(data=request.POST)

        if agenda_form.is_valid():
            agenda_form.save()
            return redirect('/agenda')
    
    context = {
        'agenda_form':agenda_form, 
        'agenda':agenda
    }

    return render(request, 'gestion_agenda.html', context)

def verAgenda(request, id_agenda):
    agenda = Agenda.objects.get(id_agenda=id_agenda)
    return render(request, "verAgenda.html", {"agenda":agenda})

def editarAgenda(request, id_agenda):
    queryset = Agenda.objects.get(id_agenda=id_agenda)
    agenda_form_update = AgendaFormUpdate(instance=queryset)
    if request.method == 'POST':
        agenda_form_update = AgendaFormUpdate(request.POST, instance=queryset)
        if agenda_form_update.is_valid():
            agenda_form_update.save()
            return redirect('/agenda')
    
    context = {
		'agenda_form_update':agenda_form_update,
	}
    return render(request, 'editarAgenda.html', context)

def eliminarAgenda(request, id_agenda):
    agenda = Agenda.objects.get(id_agenda=id_agenda)
    agenda.delete()

    return redirect('/agenda')

agenda/templates/editarAgenda.html
{% extends "./base.html" %} 
{% block title %}Edicion AGENDA {%endblock%} 
{% block body %}
{% load crispy_forms_tags %}
<h2>EDICION DE AGENDA</h2>

<form action="" method="POST">
{% csrf_token %} 
{{ agenda_form_update|crispy}}
<button type="submit" class="btn btn-success btn-block text-white">
  Guardar
</button>
</form>
{% endblock %}

agenda/templates/gestion_agenda.html
{% extends "./gestionBase.html" %} 
{% block new_title%} GESTION DE AGENDA{%endblock%} 
{% block titulo_formulario %} CARGA DE AGENDA {% endblock %} 

{% block formulario %} 
{% csrf_token %} {% load crispy_forms_tags %} 
{{ agenda_form|crispy}}
{% endblock %} 

{% block titulo_informacion%} INFORMACION DE AGENDA {%endblock%} 

{% block titulo_columnas %}
<th>ID</th>
<th>FFCHA Y HORA</th>
<th>DESCRIPCION</th>
<th>PERSONAL</th>
{%endblock%} 

{% block contenido_tabla%} 
{% for age in agenda%}
<tr>
    <td>{{age.id_agenda}}</td>
    <td>{{age.fecha_hora}}</td>
    <td>{{age.descripcion}}</td>
    <td>{{age.id_personal}}</td>
  <td>
    <a
      href="{% url 'agenda:ver_agenda' age.id_agenda%}"
      class="btn btn-success"
      >Ver</a
    >
  </td>
  <td>
    <a
      href="{% url 'agenda:editar_agenda' age.id_agenda%}"
      class="btn btn-info"
      >Editar</a
    >
  </td>
  <td>
    <button
      type="button"
      class="btn btn-danger"
      data-toggle="modal"
      data-target="#exampleModal"
    >
      Eliminar
    </button>
    <div
      class="modal fade"
      id="exampleModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">
              Confirmar Eliminación
            </h5>
            <button
              type="button"
              class="close"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">¿Desea eliminar esta Agenda?</div>
          <div class="modal-footer">
            <button
              type="button"
              class="btn btn-secondary"
              data-dismiss="modal"
            >
              Cerrar
            </button>
            <a
              href="{% url 'agenda:eliminar_agenda' age.id_agenda%}"
              class="btn btn-danger"
              >Eliminar</a
            >
          </div>
        </div>
      </div>
    </div>
  </td>
</tr>
{% endfor %} {% endblock %}

agenda/templates/verAgenda.html
{% extends "./base.html" %}
{% block title %}Edicion AGENDA {%endblock%}
{% block body %}

<div class="col-sm-12 col-md-6 col-lg-8 col-xl-8" bg-color="#80000">
  <h2>INFORMACION DE AGENDA </h2>
  <table class="table table-info">
    <thead>
      <th>Tipo</th>
      <th>Dato</th>
    </thead>
    <tbody>
      <tr>
        <td>ID</td>
        <td>{{agenda.id_agenda}}</td>
      </tr>
      <tr>
        <td>FECHA Y HORA</td>
        <td>{{agenda.fecha_hora}}</td>
      </tr>
      <tr>
        <td>DESCRIPCION</td>
        <td>{{agenda.descripcion}}</td>
      </tr>
      <tr>
        <td>ID PERSONAL</td>
        <td>{{agenda.id_personal}}</td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}