ClassManager/ClassManager/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

curso/urls.py
from django.urls import path
from . import views

app_name = 'curso'

urlpatterns = [
    path('', views.curso, name='curso'),
    path('verCurso/<id_curso>', views.verCurso, name='ver_curso'),
    path('editarCurso/<id_curso>/', views.editarCurso, name='editar_curso'),
    path('eliminarCurso/<id_curso>/', views.eliminarCurso, name='eliminar_curso'),
]

gestion_alumnos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('', include('index.urls')),
    path('alumnos/', include('alumnado.urls')),
    path('asistencia/', include('asistencia.urls')),
    path('curso/', include('curso.urls')),
    path('notas/', include('notas.urls')),
    path('especialidad/', include('especialidad.urls')),
    path('materias/', include('materia.urls')),
    path('personal/', include('personal.urls')),
    path('agenda/', include('agenda.urls'))
]

curso/models.py
from django.db import models
from materia import models as materias_models


# Create your models here.
class Curso(models.Model):
    id_curso = models.AutoField(primary_key=True)
    Annio = models.CharField(max_length=5)
    Division = models.CharField(max_length=4)
    id_materia = models.ForeignKey(materias_models.Materia, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        texto = "{0}, {1}"
        return texto.format(self.Annio, self.Division)

curso/forms.py
from django import forms
from .models import Curso

class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso
        fields = ['id_curso', 'Annio', 'Division', 'id_materia']

class CursoFormUpdate(forms.ModelForm):
    class Meta:
        model = Curso
        fields = ['id_curso', 'Annio', 'Division', 'id_materia']

curso/views.py
from django.shortcuts import render, redirect
from .models import Curso
from .forms import CursoForm, CursoFormUpdate

# Create your views here.
def curso(request):
    curso_form = CursoForm()
    curso = Curso.objects.all()

    if request.method == 'POST':
        curso_form = CursoForm(data=request.POST)

        if curso_form.is_valid():
            curso_form.save()
            return redirect('/curso')
    
    context = {
        'curso' : curso,
        'curso_form' : curso_form
    }
    return render(request, 'gestion_curso.html', context)

def verCurso(request, id_curso):
    curso = Curso.objects.get(id_curso=id_curso)
    return render(request, "verCurso.html", {"curso":curso})

def editarCurso(request, id_curso):
    queryset = Curso.objects.get(id_curso=id_curso)
    Ecurso_form = CursoFormUpdate(instance=queryset)
    if request.method == 'POST':
        Ecurso_form = CursoFormUpdate(request.POST, instance=queryset)
        if Ecurso_form.is_valid():
            Ecurso_form.save()
            return redirect('/curso')
    
    context = {
		'Ecurso_form':Ecurso_form,
	}
    return render(request, 'editarCurso.html', context)

def eliminarCurso(request, id_curso):
    curso = Curso.objects.get(id_curso=id_curso)
    curso.delete()

    return redirect('/curso')

curso/templates/editarCurso.html
{% extends "./base.html" %} 
{% block title %}Edicion CURSO {%endblock%} 
{% block body %}
{% load crispy_forms_tags %}
<h2>EDICION DE curso</h2>

<form action="" method="POST">
{% csrf_token %} 
{{ Ecurso_form|crispy}}
<button type="submit" class="btn btn-success btn-block text-white">
  Guardar
</button>
</form>
{% endblock %}

curso/templates/gestion_curso.html
{% extends "./gestionBase.html" %} 
{% block new_title%} GESTION DE CURSOS{%endblock%} 
{% block titulo_formulario %} CARGA DE CURSOS {% endblock %} 

{% block formulario %} 
{% csrf_token %} {% load crispy_forms_tags %} 
{{ curso_form|crispy}}
{% endblock %} 

{% block titulo_informacion%} INFORMACION DE CURSOS {%endblock%} 

{% block titulo_columnas %}
<th>id_curso</th>
<th>AÑO</th>
<th>Division</th>
{%endblock%} 

{% block contenido_tabla%} 
{% for cur in curso%}
<tr>
  <td>{{cur.id_curso}}</td>
  <td>{{cur.Annio}}</td>
  <td>{{cur.Division}}</td>
  <td>
    <a
      href="{% url 'curso:ver_curso' cur.id_curso%}"
      class="btn btn-success"
      >Ver</a
    >
  </td>
  <td>
    <a
      href="{% url 'curso:editar_curso' cur.id_curso%}"
      class="btn btn-info"
      >Editar</a
    >
  </td>
  <td>
    <button
      type="button"
      class="btn btn-danger"
      data-toggle="modal"
      data-target="#exampleModal"
    >
      Eliminar
    </button>
    <div
      class="modal fade"
      id="exampleModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">
              Confirmar Eliminación
            </h5>
            <button
              type="button"
              class="close"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">¿Desea eliminar este Curso?</div>
          <div class="modal-footer">
            <button
              type="button"
              class="btn btn-secondary"
              data-dismiss="modal"
            >
              Cerrar
            </button>
            <a
              href="{% url 'curso:eliminar_curso' cur.id_curso%}"
              class="btn btn-danger"
              >Eliminar</a
            >
          </div>
        </div>
      </div>
    </div>
  </td>
</tr>
{% endfor %} {% endblock %}

curso/templates/verCurso.html
{% extends "./base.html" %}
{% block title %}Edicion Alumno {%endblock%}
{% block body %}

<div class="col-sm-12 col-md-6 col-lg-8 col-xl-8" bg-color="#80000">
  <h2>INFORMACION DE ASISTENCIA </h2>
  <table class="table table-info">
    <thead>
      <th>Tipo</th>
      <th>Dato</th>
    </thead>
    <tbody>
      <tr>
        <td>ID</td>
        <td>{{asistencia.id_asistencia}}</td>
      </tr>
      <tr>
        <td>FECHA</td>
        <td>{{asistencia.fechaA}}</td>
      </tr>
      <tr>
        <td>HORA</td>
        <td>{{asistencia.horaA}}</td>
      </tr>
      <tr>
        <td>CONDICION</td>
        <td>{{asistencia.condicion}}</td>
      </tr>
      <tr>
        <td>CANTIDAD DE ASISTENCIAS</td>
        <td>{{asistencia.cantidadA}}</td>
      </tr>
      <tr>
        <td>TURNO</td>
        <td>{{asistencia.turno}}</td>
      </tr>
      <tr>
        <td>REINTEGRADO</td>
        <td>{{asistencia.reintegrado}}</td>
      </tr>
      <tr>
        <td>id_alumno</td>
        <td>{{asistencia.id_alumno}}</td>
      </tr>
      <tr>
        <td>evento</td>
        <td>{{asistencia.evento}}</td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}