ClassManager/ClassManager/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

curso/urls.py
from django.urls import path
from . import views

app_name = 'curso'

urlpatterns = [
    path('', views.curso, name='curso'),
    path('verCurso/<id_curso>', views.verCurso, name='ver_curso'),
    path('editarCurso/<id_curso>/', views.editarCurso, name='editar_curso'),
    path('eliminarCurso/<id_curso>/', views.eliminarCurso, name='eliminar_curso'),
]

gestion_alumnos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('', include('index.urls')),
    path('alumnos/', include('alumnado.urls')),
    path('asistencia/', include('asistencia.urls')),
    path('curso/', include('curso.urls')),
    path('notas/', include('notas.urls')),
    path('especialidad/', include('especialidad.urls')),
    path('materias/', include('materia.urls')),
    path('personal/', include('personal.urls')),
    path('agenda/', include('agenda.urls'))
]

notas/urls.py
from django.urls import path
from . import views

app_name = 'notas'

urlpatterns = [
    path('', views.notas, name='notas'),
    path('verNota/<id_nota>', views.verNota, name='ver_nota'),
    path('editarNota/<id_nota>/', views.editarNota, name='editar_nota'),
    path('eliminarNota/<id_nota>/', views.eliminarNota, name='eliminar_nota'),
]

notas/models.py
from django.db import models
from materia import models as materias_models
from alumnado import models as alumnos_models

# Create your models here.
class Notas(models.Model):
    id_nota = models.AutoField(primary_key=True)
    valor = models.CharField(max_length=3)
    AnnioCursada = models.CharField(max_length=5)
    instancia = models.CharField(max_length=30)
    fechaNota = models.DateField()
    id_alumno = models.ForeignKey(alumnos_models.Alumno, on_delete=models.CASCADE)
    id_materia = models.ForeignKey(materias_models.Materia, on_delete=models.CASCADE)
    

    def __str__(self):
        texto = "{0}"
        return texto.format(self.valor)

notas/forms.py
from django import forms
from .models import Notas

class NotasForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['fechaNota'].widget = forms.widgets.DateInput(
            attrs={
                'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)',
                'class': 'form-control'
                }
            )

    class Meta:
        model = Notas
        fields = ['id_nota', 'valor', 'instancia', 'fechaNota',  'AnnioCursada', 'id_materia', 'id_alumno']


class NotasFormUpdate(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['fechaNota'].widget = forms.widgets.DateInput(
            attrs={
                'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)',
                'class': 'form-control'
                }
            )

    class Meta:
        model = Notas
        fields = ['id_nota', 'valor', 'instancia', 'fechaNota', 'AnnioCursada', 'id_materia', 'id_alumno']

notas/views.py
from django.shortcuts import render, redirect
from .models import Notas
from .forms import NotasForm, NotasFormUpdate

# Create your views here.
def notas(request):
    notas_form = NotasForm()
    notas = Notas.objects.all()


    if request.method == 'POST':
        notas_form = NotasForm(data=request.POST)

        if notas_form.is_valid():
            notas_form.save()
            return redirect('/notas')
    
    context = {
        'notas_form' :notas_form,
        'notas': notas
    }
    return render(request, 'gestion_notas.html', context)

def verNota(request, id_nota):
    notas = Notas.objects.get(id_nota=id_nota)
    return render(request, "verNotas.html", {"notas":notas})

def editarNota(request, id_nota):
    queryset = Notas.objects.get(id_nota=id_nota)
    Enota_form = NotasFormUpdate(instance=queryset)
    if request.method == 'POST':
        Enota_form = NotasFormUpdate(request.POST, instance=queryset)
        if Enota_form.is_valid():
            Enota_form.save()
            return redirect('/notas')
    
    context = {
		'Enota_form':Enota_form,
	}
    return render(request, 'editarNotas.html', context)

def eliminarNota(request, id_nota):
    notas = Notas.objects.get(id_nota=id_nota)
    notas.delete()

    return redirect('/notas')

notas/templates/editarNotas.html
{% extends "./base.html" %} 
{% block title %}Edicion ASISTENCIA {%endblock%} 
{% block body %}
{% load crispy_forms_tags %}
<h2>EDICION DE NOTAS</h2>
<form action="" method="POST">
{% csrf_token %} 
{{ Enota_form|crispy}}
<button type="submit" class="btn btn-success btn-block text-white">
  Guardar
</button>
</form>
{% endblock %}

notas/templates/gestion_notas.html
{% extends "./base.html" %} {% block title %}GESTION DE NOTAS{%endblock%} 
{% block body %}{% load crispy_forms_tags %}
<div class="row">
  <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4 bg-info">
    <h2>GESTION DE NOTAS</h2>
    <div class="card bg-info">
      <div class="card-body bg-info">
        <form action="" method="POST">
          {% csrf_token %} {{ notas_form|crispy}}

          <button type="submit" class="btn btn-success btn-block text-white">
            Guardar
          </button>
        </form>
      </div>
    </div>
  </div>
  <div class="col-sm-12 col-md-6 col-lg-8 col-xl-8 bg-info">
    <h1>INFORMACION DE NOTAS</h1>
    <div class="table-responsive py-2">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>id_nota</th>
            <th>VALOR</th>
            <th>id_materia</th>
            <th>id_alumno</th>
            <th colspan="3">
              <center>MENU</center>
            </th>
          </tr>
        </thead>
        <tbody>
          {% for nota in notas%}
          <tr>
            <td>{{nota.id_nota}}</td>
            <td>{{nota.valor}}</td>
            <td>{{nota.id_materia}}</td>
            <td>{{nota.id_alumno}}</td>
            <td>
              <a
                href="{% url 'notas:ver_nota' nota.id_nota%}"
                class="btn btn-success"
                >Ver</a
              >
            </td>
            <td>
              <a
                href="{% url 'notas:editar_nota' nota.id_nota%}"
                class="btn btn-info"
                >Editar</a
              >
            </td>
            <td>
              <button
                type="button"
                class="btn btn-danger"
                data-toggle="modal"
                data-target="#exampleModal"
              >
                Eliminar
              </button>
              <div
                class="modal fade"
                id="exampleModal"
                tabindex="-1"
                role="dialog"
                aria-labelledby="exampleModalLabel"
                aria-hidden="true"
              >
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">
                        Confirmar Eliminación
                      </h5>
                      <button
                        type="button"
                        class="close"
                        data-dismiss="modal"
                        aria-label="Close"
                      >
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">¿Desea eliminar esta Nota?</div>
                    <div class="modal-footer">
                      <button
                        type="button"
                        class="btn btn-secondary"
                        data-dismiss="modal"
                      >
                        Close
                      </button>
                      <a
                        href="{% url 'notas:eliminar_nota' nota.id_nota%}"
                        class="btn btn-danger"
                        >Eliminar</a
                      >
                    </div>
                  </div>
                </div>
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}

notas/templates/verNotas.html
{% extends "./base.html" %}
{% block title %}Vision Notas {%endblock%}
{% block body %}

<div class="col-sm-12 col-md-6 col-lg-8 col-xl-8" bg-color="#80000">
  <h2>INFORMACION DE NOTAS </h2>
  <table class="table table-info">
    <thead>
      <th>Tipo</th>
      <th>Dato</th>
    </thead>
    <tbody>
      <tr>
        <td>ID</td>
        <td>{{notas.id_nota}}</td>
      </tr>
      <tr>
        <td>VALOR</td>
        <td>{{notas.valor}}</td>
      </tr>
      <tr>
        <td>FECHA DE LA NOTA</td>
        <td>{{notas.fechaNota}}</td>
      </tr>
      <tr>
        <td>INSTANCIA</td>
        <td>{{notas.instancia}}</td>
      </tr>
      <tr>
        <td>AÑO CURSADA</td>
        <td>{{notas.AnnioCursada}}</td>
      </tr>
      <tr>
        <td>MATERIA</td>
        <td>{{notas.id_materia}}</td>
      </tr>
      <tr>
        <td>id_alumno</td>
        <td>{{notas.id_alumno}}</td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}